dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.2
  - Openzeppelin/openzeppelin-contracts@4.1.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.2'
      - '@openzeppelin=Openzeppelin/openzeppelin-contracts@4.1.0'
dotenv: .env
networks:
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
